DaoException: added FAIL_TO_UPDATE_DB and UNIQUENESS_VIOLATED; added static method fromSQLException. DaoManager: update DB_VERSION_VALUE to 22; skip rollback logic for updateDB as database structure update always commit immediately; Changed table structure for securities and prices; changed SECURITY_PRICE to SECURITYID_PRICE. SecurityDao: mapping empty ticker to null in db. SecurityIDPriceDao: (renamed from SecurityPriceDao), took out ticker. EditSecurityPriceDialogController: ... EditTransactionDialogControllerNew: ... HoldingDialogController: ... MainController: more meaningful logAndDisplayException, ... MainModel:
MainTest: better output.